### ISSUE TITLE
Add jpegli codec to the comparison 

### ISSUE THREAD

**Issue by eclipseo** [webmproject/codec-compare#12]
Hello,

Could you add Jpegli codec by Google Zurich to a future comparison?

It is not a next generation codec like your existing codecs but supposedly brings significant improvements over mozjpeg and libjpeg-turbo. 

I'd do it myself but I don't have access to a "AMD EPYC Rome/Milan, 48 vCPU, 192 GB RAM, 1024 GB SSD".

**Comment by y-guyon** [comment]
I agree it would be good to have data points for MozJPEG, jpegli, jpeg-turbo and sjpeg.  
Not sure when I will have the time to publish them though.

**Comment by y-guyon** [comment]
**jpegli** compared to **sjpeg** on 2-3 megapixels images at [web bpp range](https://github.com/webmproject/codec-compare/wiki/Bits-per-pixel-of-Internet-images):  
https://storage.googleapis.com/demos.webmproject.org/webp/cmp/2024_09_03/index.html?batch=batches/jpegsimple_420_8.json&batch=batches/jpegli_420_0.json#sjpeg+4%3A2%3A0+method+8-bpp=0.38..3.32&jpegli+4%3A2%3A0-original_name=b3e0ffe4fffde7ffd7fbd2b2f1

Multiple formats and chroma subsamplings are available in the Presets in the left navigation bar.
